OrdererOrgs:
  - Name: OrdererOrg
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: JIO
    Domain: jio.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Airtel
    Domain: airtel.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1